[env]
RUST_MIN_STACK = "536870912"

[alias]
run-dev = "run --features commerce,wholesale,contact-center,addon-sbc --bin rustpbx -- --conf config.toml.dev"
test-dev = "test --features commerce,wholesale,contact-center,addon-sbc"
check-dev = "check --features commerce,wholesale,contact-center,addon-sbc"

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-Wl,-no_compact_unwind"]
